### ISSUE TITLE
Service Account Limit restriction

### ISSUE THREAD

**Issue by patan12** [GoogleCloudPlatform/alloydb-java-connector#455] opened 2024-03-04 11:30 UTC
### Question

We have service account whose length is 64. Its not allowing us to add service accounts whose length is 64. When we are adding in terraform, its trimming the last 'm' char

Even from GOOGLE CLI, for adding users same behavior is shown.

sa-vehicle-catalog-dlr-micrsvc@abcd-9fa483bbe1b9a050aa74e7x5.iam

It adding as

sa-vehicle-catalog-dlr-micrsvc@abcd-9fa483bbe1b9a050aa74e7x5.ia

what are the implications here.

- what is the user name I need to give in connection properties
- or is it a bug that needs to fixed
- I tried to authenticate using IAM AUTH using alloy db connector. Its not working as the last char is trimmed

**Comment by ttosta-google** [comment] 2024-03-05 01:09
Thanks @patan12 for your question. I am currently investigating the issue and will provide an update as soon as possible.

**Comment by ttosta-google** [comment] 2024-03-05 19:12
Hello @patan12,

I've confirmed that Terraform is working as expected since Postgres roles (users) can only have a maximum length of 63 characters. This limit is confirmed in a [discussion](https://github.com/hashicorp/terraform-provider-google/issues/15520) where the Cloud SQL team (also applicable to AlloyDB) decided against increasing it due to its potential impact on existing databases, as per Postgres team guidelines.

The only viable solution is to utilize an alternative service account with a character count below 63.

Since this is not a Connector-related issue, I am closing this discussion.

Please feel free to open new issues if needed.

Thanks.

**Closed by ttosta-google** 2024-03-05 19:12 UTC
Labels: type: question
